config/routes.rb
Gereditais::Application.routes.draw do

	resources :ceps
	
	resources :sessions
	resources :users

	resources :modalidades

	resources :editals do
		member do
			get 'edital'
		end

		resources :downloads

		resources :uploads do
			member do
				get 'upload'
			end
		end

		resources :impugnations do
			member do
				get 'impugnation'
			end
		end

		resources :microposts

	end

	match 'signup' => 'users#new', :as => :signup
	match 'logout' => 'sessions#destroy', :as => :logout
	match 'login' => 'sessions#new', :as => :login

	match 'products' => redirect('http://apps.ghc.com.br/gerestoque'), :as=>:products

	root :to=> "editals#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/edital.rb
# encoding: utf-8

class Edital < ActiveRecord::Base

	belongs_to :modalidade
	has_many :upload , :dependent => :destroy
	has_many :impugnation , :dependent => :destroy
	has_many :download , :dependent => :destroy
	has_many :user , :through=> :download
	has_many :micropost , :dependent => :destroy

	scope :nabertos ,  where("data_abertura >= ?", Date.today)
	scope :publicados , nabertos.where(:publicado => true)


	scope :find_by_licitacao, lambda {|licitacao| 
			if licitacao.split('/').size==2
				where(:numero_licitacao => licitacao.split('/').first, 
						:ano_licitacao => licitacao.split('/').last)
			else
				where(:numero_licitacao => licitacao)
			end
	}

#	scope :find_by_licitacao, lambda {|licitacao| {
#						:conditions => {:numero_licitacao => licitacao.split('/').first, 
#     					:ano_licitacao => licitacao.split('/').last}}}

#	scope :find_by_licitacao, lambda {|licitacao| 
#				{
#					:conditions => {
#							:numero_licitacao => licitacao.split('/').first, 
#     						:ano_licitacao => licitacao.split('/').last
#							}
#				}
#	}


 	search_methods :find_by_licitacao

	attr_accessible :numero_licitacao, :ano_licitacao, :modalidade_id, :titulo, :descricao,
	 :aviso, :data_publicacao, :data_abertura, :publicado, :edital, :hora_abertura


	validates_presence_of :numero_licitacao, :ano_licitacao, :modalidade_id, 
								:titulo, :descricao, :data_publicacao, :data_abertura, :edital, :hora_abertura

	validate :valida_datas
	validate :valida_hora_abertura

	HORA  = /\d{2}\:\d{2}/
	validates_format_of :hora_abertura, :with =>/^(#{HORA})$/, :allow_blank => false, :message => "hora abertura formato inválido"

	###################################################################################
	#attachment_virtual_path = "/system/attachments/:id/:basename.:extension"
	#attachment_real_path = ":rails_root/public" + attachment_virtual_path
 	#has_attached_file :edital, :path => attachment_real_path, :url => attachment_virtual_path
# 	has_attached_file :edital, :url => "/assets/editals/:id/:basename.:extension", :path => ":rails_root/public/assets/editals/:id/:style/:basename.:extension" 

# 	has_attached_file :edital, 
# 							:url => "/system/editals/:id/:basename.:extension", 
# 							:path => ":rails_root/public/system/editals/:id/:basename.:extension" 


 	has_attached_file :edital, 
 							:path => ":rails_root/non-public/system/editals/:id/:basename.:extension",
 							:url => "/:class/:id/:attachment" 


	validates_numericality_of :numero_licitacao, :ano_licitacao , :modalidade_id

	validates_attachment_presence :edital
	validates_attachment_content_type :edital, :content_type => ['application/pdf','application/zip'],
												:message => 'Somente pdf. e zip.'
	validates_attachment_size :edital, :less_than => 200.megabytes

	#####################################################################################

	def licitacao
	  [self.numero_licitacao, self.ano_licitacao].join('/')
	end

	def publicacao
		self[:data_publicacao].to_date
	end

	def abertura
		self[:data_abertura].to_time
	end

	def valida_hora_abertura
		if self.hora_abertura == "00:00"
			errors.add(:hora_abertura,"'Valor inválido para hora de abertura'")
			return false
		end
	end

	def valida_datas
		begin
			if self[:data_abertura] < self[:data_publicacao]
				errors.add(:data_abertura,"precisa ser maior que data de publicação")
				return false
			end
		rescue
		end
	end

	def data_abertura=(data)
		begin
			date=data.split("/")
			self[:data_abertura]=Date.new(date[2].to_i,date[1].to_i,date[0].to_i)
		rescue
			self[:data_abertura]=data
		end
	end

	def data_abertura
		begin
			self[:data_abertura].to_time.strftime('%d/%m/%Y')
		rescue
			self[:data_abertura]
		end
	end

	def hora_abertura
		begin
			self[:data_abertura].to_time.strftime('%H:%M')
		rescue
			""
		end
	end

	def hora_abertura=(hora)
		begin
			data=self[:data_abertura].to_date
			self[:data_abertura]=Time.parse("#{data} #{hora}")
			return true
		rescue
			return false
		end
	end


	def data_publicacao=(data)
		begin
			date=data.split("/")
			self[:data_publicacao]=Date.new(date[2].to_i,date[1].to_i,date[0].to_i)
		rescue
			self[:data_publicacao]=data
		end
	end

	def data_publicacao
		begin
			self[:data_publicacao].strftime('%d/%m/%Y')
		rescue
			self[:data_publicacao]
		end
	end

end

app/controllers/editals_controller.rb
# encoding: utf-8

class EditalsController < ApplicationController

	# filter at the top always
	before_filter :login_required, :except => [:index, :show]
	before_filter :check_admin, :except => [:index, :show, :edital]

	caches_page :index, :show
	cache_sweeper :edital_sweeper, :only=>[:create, :update, :destroy]

	def edital

		edital = Edital.find(params[:id])
		filename=filename="ghc_#{edital.modalidade.descricao.gsub(/ /,'')}_#{edital.numero_licitacao}_#{edital.ano_licitacao}.#{edital.edital_content_type.split('/')[1]}"
 
#		begin
			if session[:save]
				send_file edital.edital.path, 
										:type => edital.edital_content_type,
										:filename=>"#{filename}",
										:disposition=>'attachment', :x_sendfile=>false
				session[:save]=false
			else
				flash[:error] = "Não foi possível fazer download do edital."
		  		redirect_to new_edital_download_path(edital)
			end
#		rescue
#			flash[:error] = "erro 2"
#	  		redirect_to root_path
#		end

	end


#	def edital

#		edital = Edital.find(params[:id])

#		begin
#			if session[:save]
#				send_file edital.edital.path, :type => edital.edital_content_type
#				session[:save]=false
#			else
#				flash[:error] = "erro 1"
#		  		redirect_to new_edital_download_path(edital)
#			end
#		rescue
#			flash[:error] = "erro 2"
#	  		redirect_to root_path
#		end

#	end

#	def edital

#		begin

#			@edital=Edital.find(params[:id])
#			@download=@edital.download.new(:user_id=>current_user.id)

#			if @download.save
#				send_file @edital.edital.path, :type => @edital.edital_content_type
#			else
#				flash[:error] = "Não foi possível fazer download do Edital"
#	  			redirect_to new_edital_download_path(@edital)
#			end
#		rescue
#			flash[:error] = "Não foi possível fazer download do Edital"
#	  		redirect_to root_path
#		end

#	end


  def index

	@modalidades ||= Modalidade.scoped(:order => "descricao")

 	begin
		params[:search][:data_abertura_gte]=get_data(params[:search][:data_abertura_gte],0)
		params[:search][:data_abertura_lte]=get_data(params[:search][:data_abertura_lte],1)

		params[:search][:data_publicacao_gte]=get_data(params[:search][:data_publicacao_gte],0)
		params[:search][:data_publicacao_lte]=get_data(params[:search][:data_publicacao_lte],1)
	rescue
	end

	if logged_in? and current_user.admin?
		@search = Edital.includes(:modalidade).search(params[:search])
		@editals = @search.order("updated_at DESC").paginate(:page => params[:page], :per_page=>10)
	else
		@search = Edital.publicados.includes(:modalidade).search(params[:search])
		@editals = @search.order("updated_at DESC").paginate(:page => params[:page], :per_page=>10)
	end

    respond_to do |format|
      format.html
      format.js
    end

  end
  
  def show

	 @modalidades ||= Modalidade.scoped(:order => "descricao")

    @edital = Edital.find(params[:id])
    @upload = @edital.upload.new
  	 @impugnation = @edital.impugnation.new

	 @microposts=@edital.micropost.scoped.paginate(:page => params[:page], :per_page=>5)
	 @micropost=@edital.micropost.new

    respond_to do |format|
      format.html
      format.js
    end

  end
  
  def new

	@modalidades ||= Modalidade.scoped(:order => "descricao")
	@edital = Edital.new

  end
  
  def create

	 @modalidades ||= Modalidade.scoped(:order => "descricao")
    @edital = Edital.new(params[:edital])

	if logged_in? 
		@user_downloads= current_user.group_by_editals
	end

    if @edital.save
      flash[:notice] = "Edital criado com sucesso."
      redirect_to @edital
    else
      render :action => 'new'
    end
  end
  
  def edit

	 @modalidades ||= Modalidade.scoped(:order => "descricao")
    @edital = Edital.find(params[:id])

  end
  
  def update

	 @modalidades ||= Modalidade.scoped(:order => "descricao")
    @edital = Edital.find(params[:id])

    if @edital.update_attributes(params[:edital])
      flash[:notice] = "Edital atualizado com sucesso."
      redirect_to @edital
    else
      render :action => 'edit'
    end
  end
  
  def destroy

	 @modalidades ||= Modalidade.scoped(:order => "descricao")
    @edital = Edital.find(params[:id])

    @edital.destroy
    flash[:notice] = "Edital apagado."
    redirect_to editals_url
  end

private

	def get_data(data,tr)

		return if data.empty?

		date=data.split("/")

		hora="23:59"
		data="#{date[2].to_i}/#{date[1].to_i}/#{date[0].to_i}"

		if tr==1
			Time.parse("#{data} #{hora}")
		else
			Date.parse("#{data}")
		end

	end

end

app/helpers/editals_helper.rb
# encoding: utf-8 

module EditalsHelper

	def download_url(edital)
		edital_edital_path(edital)
	end

	def link(content,edital)
		if logged_in? 
			if current_user.admin?
				link_to content , edital
			else
				link_to content , new_edital_download_path(edital)
			end
		else
			content
		end
	end

	def wrap(content)
		raw(content.split.map{ |s| wrap_long_string(s) }.join(' '))
	end

	def get_data(date)
		if date
			begin
				data=date
				var=data.to_s.split(" ")
				data=var[0].split("-")
				"#{data[2]}/#{data[1]}/#{data[0]}"	
			rescue
				""
			end
		end
	end
private

	def wrap_long_string(text, max_width = 30)
		zero_width_space = "&#8203;"
		regex = /.{1,#{max_width}}/
		(text.length < max_width) ? text : text.scan(regex).join(zero_width_space)
	end



end

app/views/editals/_editais.html.erb
<div id="editais">
	<%= will_paginate @editals %>
		<table class="microposts" summary="User microposts">

			 <tr>
				 <th><%= sort_link @search,  :descricao, "Descrição" %></th>
				 <% if logged_in? and current_user.admin? %>			
				 	<th><%= sort_link @search,  :publicado, "Publicado" %></th>
				 <% end %>
				 <th><%= sort_link @search,  :data_publicacao, "Data Publicação" %></th>
				 <th><%= sort_link @search,  :data_abertura, "Data Abertura" %></th>
			  </tr>

				<%= render @editals %>

		</table>
	<%= will_paginate @editals %>
</div>

app/views/editals/_edital.html.erb
		<tr>

		<td>

			<div id="edital_titulo">

				<% if logged_in? %>
						<div id="link" data-url="<%=edital.edital.url%>" data-user="<%=current_user.id%>" data-id="<%= edital.id %>">
							<%= link "#{edital.modalidade.descricao} #{edital.numero_licitacao}/#{edital.ano_licitacao}", edital %>
						</div>
			<% else %>

						<div id="link">
								<%= link "#{edital.modalidade.descricao} #{edital.numero_licitacao}/#{edital.ano_licitacao}", edital %>
						</div>

			<% end %>

			</div>

			<p>

				<div class="lista_edital_descricao">
				  <%= wrap(edital.descricao) %><br />
				</div>		

				<br />

				<div class="lista_edital_aviso">
				  <%= wrap(edital.aviso) %><br />
				</div>

				<br />		

				<% if logged_in? and current_user.admin? %>			
						<%= link_to "Editar", edit_edital_path(edital) %> |
						<%= link_to "Apagar", edital, :confirm => 'Tem Certeza?', :method => :delete %> |
				<% end %>
				<%= link_to "Exibir", edital %>
			</p>
		</td>

		<% if logged_in? and current_user.admin? %>			
			<td><%= (edital.publicado) ? "Sim" : "Não" %></td>
		<% end %>
		<td><%= edital.data_publicacao %></td>
		<td><%= edital.data_abertura %></td>
		</tr>

app/views/editals/_form.html.erb
<%= form_for @edital, :html => { :multipart => true }  do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :numero_licitacao %><br />
    <%= f.text_field :numero_licitacao %>
  </p>
  <p>
    <%= f.label :ano_licitacao %><br />
    <%= f.text_field :ano_licitacao %>
  </p>
  <p>
    <%= f.label :modalidade_id %><br />
	<%= f.select  "modalidade_id",  @modalidades.map { |m| [ m.descricao, m.codigo ]}, {:include_blank => ''}%>
    
  </p>
  <p>
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </p>

  <p>
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </p>

  <p>
    <%= f.label :aviso %><br />
    <%= f.text_area :aviso%>
  </p>

<% if @edital.upload.empty? %>
 <p>
  <%= f.label :edital, "Selecione o arquivo para Upload" %><br /><br />
  <%= f.file_field :edital%>
 </p>
<% end%>

 <p>
 		<%= f.label :data_publicacao, "Data da Publicação" %><br />
		<%= f.text_field :data_publicacao, :value=>@edital.data_publicacao , :class=>"data", :disabled=>@edital.upload.any? %>
  </p>

  <p>
		<%= f.label :data_abertura , "Data da Abertura" %><br />
		<%= f.text_field :data_abertura, :value=> @edital.data_abertura , :class=>"data", :disabled=>@edital.upload.any?  %>
  </p>

  <p>
		<%= f.label :hora_abertura , "Hora da Abertura" %><br />
		<%= f.text_field :hora_abertura, :value=> @edital.hora_abertura , :class=>"hora", :disabled=>@edital.upload.any?  %>
  </p>


  <p>
    <%= f.label :publicado %><br />
    <%= f.check_box :publicado %>
  </p>

  <p><%= f.submit "Salvar", :class=>"g-button"%></p>
<% end %>

app/views/editals/_search.html.erb
<div id="search" >

		<%= form_for @search do |f| %>

<fieldset class="round"> 
 <legend>Pesquisa</legend> 

		  <p>
			<%= f.label :modalidade_id_equals, "Modalidade:" %><br />
			<%= f.select  "modalidade_id_equals",  @modalidades.map { |m| [ m.descricao, m.codigo ]}, {:include_blank => ''}, :class=>"clearme" %>
		  </p>

		 <p>
			<%= f.label :find_by_licitacao, "Licitação:" %><br /> 
			<%= f.text_field :find_by_licitacao, :class=>"clearme", :placeholder=>"Formato NNN/YYYY" %>
		 </p>

		 <p>
			<%= f.label :descricao_or_aviso_contains, "Descrição do Edital:" %><br />
			<%= f.text_field :descricao_or_aviso_contains, :class=>"clearme ", :placeholder=>"Executa pesquisa nos campos descrição e aviso	" %>
		 </p>

			<p>
				<%= f.label :data_publicacao_gte, "Data da publicação:" %><br />
				<%= f.text_field :data_publicacao_gte, :value=>get_data(@search.data_publicacao_gte) , :class=>"data clearme", :placeholder=>"de" %>

				<%= f.label :data_publicacao_lte, "-" %>
				<%= f.text_field :data_publicacao_lte, :value=>get_data(@search.data_publicacao_lte) , :class=>"data clearme", :placeholder=>"até" %>
			</p>

			<p>
				<%= f.label :data_abertura_gte, "Data da abertura:" %><br />
				<%= f.text_field :data_abertura_gte, :value=>get_data(@search.data_abertura_gte) , :class=>"data clearme", :placeholder=>"de" %>

				<%= f.label :data_abertura_lte, "-" %>
				<%= f.text_field :data_abertura_lte, :value=>get_data(@search.data_abertura_lte) , :class=>"data clearme", :placeholder=>"até" %>
			</p>

			<% if logged_in? and current_user.admin? %>
			  <p>
				<%= f.label :publicado, "Somente os não Publicados:" %><br />
				<%= f.check_box :publicado_is_false , :class=>"clearme"%>
			  </p>

			<% end %>
 
		<%= f.submit  "Pesquisar", :class=>"g-button" %>  <%=f.submit  "Limpar", :type=>"reset", :class=>"reset_search g-button", :id=>"reset_search"  %> <br /> 

		<% end %>
</fieldset> 	
</div>

app/views/editals/_show.html.erb
<p>
	<h2><%= link "Download da #{@edital.modalidade.descricao} #{@edital.numero_licitacao}/#{@edital.ano_licitacao}", @edital %></h2>
</p>
<p>
  <strong>Numero Licitacao:</strong>
  <%= @edital.numero_licitacao %>
</p>
<p>
  <strong>Ano Licitacao:</strong>
  <%= @edital.ano_licitacao %>
</p>
<p>
  <strong>Modalidade:</strong>
  <%= @edital.modalidade.descricao %>
</p>
<p>
  <strong>Titulo:</strong>
		<div id="edital_titulo">
		   <%= wrap(@edital.titulo) %>
		</div>
 </p>

<p>
  <strong>Descricao:</strong>
		<div id="edital_descricao">
		  <%= wrap(@edital.descricao) %>
		</div>
</p>

<br />

	<p>
		<strong>Aviso:</strong>
		<div id="edital_aviso">
			<%= wrap(@edital.aviso) %>
		</div>
	</p>

<br />

<p>
  <strong>Data Publicacao:</strong>
  <%= @edital.data_publicacao %>
</p>

<p>
  <strong>Data Abertura:</strong>
  <%= @edital.data_abertura %>, as  <%= @edital.hora_abertura %>
</p>

<p>
  <strong>Publicado:</strong>
  <%= (@edital.publicado) ? "Sim" : "Não" %>
</p>

<p>
   <% if logged_in? %>
				<% if current_user.admin? %>			
						<%= link_to "Editar", edit_edital_path(@edital) %> |
						<%= link_to "Apagar", @edital, :confirm => 'Tem certeza que quer apagar?', :method => :delete %> |
				<% end %>
   <% end %>
  <%= link_to "Exibir Todos os Editais", editals_path %>
</p>

app/views/editals/edit.html.erb
<% title "Editar Edital" %>

<%= render 'form' %>

<p>
  <%= link_to "Exibir", @edital %> |
  <%= link_to "Exibir Todos", editals_path %>
</p>

app/views/editals/index.html.erb
<% title "Editais" %>

	<% if logged_in? %>
			<% if current_user.admin? %>			
				<div>
					<p><%= link_to "Novo Edital", new_edital_path , :class => "novo_edital_button round" %></p>
				</div>
			<% end %>			
	<% end %>

	<div id="panel"> 
			<%= render 'search'%>
	</div> 
	
	<div class="slide">
		<a href="#" class="btn-slide" >Pesquisar</a>
	</div> 

	<table class="front" summary="Lista de Editais">
		<tr>
			<td class="main">
				<%= render 'editais' %>				
			</td>
			<% if logged_in? %>
				<td class="sidebar round">
					<div id="stats" class="sidebar round">					
						<%= render 'shared/stats' %>
					</div>
				</td>
			<% end %>
		</tr>
	</table>

app/views/editals/index.js.erb
$('#editais').html("<%= escape_javascript( render 'editais' )%>");
$('#user_downloads').html("<%= escape_javascript( render 'downloads/downloads' )%>");

app/views/editals/new.html.erb
<% title "Novo Edital" %>

<p><%= link_to "Lista de Editais", editals_path %></p>

<%= render 'form' %>

<p><%= link_to "Lista de Editais", editals_path %></p>

app/views/editals/show.html.erb
<% title "Dados do Edital: #{@edital.titulo}" %>

<table class="front" summary="For signed-in users">

	<tr>
		<td class="main">

			<%=render 'show'%>

			<% if logged_in? %>
				<%= render 'microposts/form' %>
			<% end %>

			<%= render 'microposts/microposts' %>				

		</td>

		<% if logged_in? %>
				<td class="sidebar round">
							<div id="stats" class="round">					
								<%= render 'shared/stats' %>
							</div>
							<br />
							<% flash.each do |name, msg| %>
							  <%= content_tag :div, msg, :class => "#{name} round" %>
							<% end %>
			
							<div id="uploads" class="round">	 
								<%=render 'uploads/uploads'%>
							</div>
							<br />
							<div id="impugnations" class="round">	 
								<%=render 'impugnations/impugnations'%>
							</div>
				</td>
		<% end %>
	</tr>


</table>

app/views/editals/show.js.erb
$('#microposts').html("<%= escape_javascript(render 'microposts/microposts')%>");
$('#user_downloads').html("<%= escape_javascript( render 'downloads/downloads' )%>");