config/routes.rb
Gereditais::Application.routes.draw do

	resources :ceps
	
	resources :sessions
	resources :users

	resources :modalidades

	resources :editals do
		member do
			get 'edital'
		end

		resources :downloads

		resources :uploads do
			member do
				get 'upload'
			end
		end

		resources :impugnations do
			member do
				get 'impugnation'
			end
		end

		resources :microposts

	end

	match 'signup' => 'users#new', :as => :signup
	match 'logout' => 'sessions#destroy', :as => :logout
	match 'login' => 'sessions#new', :as => :login

	match 'products' => redirect('http://apps.ghc.com.br/gerestoque'), :as=>:products

	root :to=> "editals#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/download.rb
# encoding: utf-8

class Download < ActiveRecord::Base

	belongs_to :edital
	belongs_to :user
	
	attr_accessible :edital_id, :user_id
	
end

app/controllers/downloads_controller.rb
# encoding: utf-8

class DownloadsController < ApplicationController

	before_filter :login_required
	before_filter :check_admin_for_download

	def index
		@title="Downloads"
	end

	def new
	
		@title="Novo Download"

		if params[:edital_id] 
			@edital=Edital.find(params[:edital_id])
			@download=@edital.download.new

			respond_to do |format|
				format.html
				format.js
			end
			
		else
			redirect_to root_path
		end

	end

#	def create

#		@edital=Edital.find(params[:edital_id])

#		respond_to do |format|
#			format.html 
#			format.js
#		end

#	end


	def create

		session[:save]=false

		if params[:edital_id] 

			@edital=Edital.find(params[:download][:edital_id])

			agora = Time.now 
			abertura = @edital.abertura 
			
			if agora < abertura

				@download=@edital.download.new(params[:download])

				if @download.save
					session[:save]=true
					respond_to do |format|
						format.html 
						format.js
					end
				else
					flash[:error] = "Download não efetuado."
#					redirect_to @edital
				end
			else
			  flash[:error] = "Após data da abertura não é possivel efetuar download"
#			  redirect_to @edital
			end

		else
#			redirect_to root_path
		end

	end



#	def create

#		session[:save]=false

#		if params[:edital_id] 

#			@edital=Edital.find(params[:edital_id])

#			agora = Time.now 
#			abertura = @edital.abertura 
#			
#			if agora < abertura

#				@download=@edital.download.new(params[:download])

#				if @download.save
#					session[:save]=true
#					respond_to do |format|
#						format.html 
#						format.js
#					end
#				else
#					flash[:error] = "Download não efetuado."
##					redirect_to @edital
#				end
#			else
#			  flash[:error] = "Após data da abertura não é possivel efetuar download"
##			  redirect_to @edital
#			end

#		else
##			redirect_to root_path
#		end

#	end

	def show

		 respond_to do |format|
		   format.html
		   format.js
		 end

	end


end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/views/downloads/_count.html.erb
	<%= pluralize(@edital.download.count, 'Download') %>
	
	<% downloads ||= @edital.download.group(:user_id).select("user_id, count(user_id) as count_download").paginate(:page => params[:download_edital], :per_page=>10)%>
	
	<ul>

	<% for download in downloads %>
		<li>
			<%= "#{download.user.razao_social}, #{download.user.username}" %> <%= pluralize(download.count_download, "Download") %>
		</li>
	<% end%>

	</ul>

	<%= will_paginate downloads, :param_name => 'download_edital' %>

app/views/downloads/_download.html.erb
	<li>
		<%= "#{download.edital.modalidade.descricao} #{download.edital.numero_licitacao}/#{download.edital.ano_licitacao}" %>

		<%= pluralize(download.edital_count, "Download") %>
	</li>

app/views/downloads/_downloads.html.erb
<% if logged_in? %>

<%	@user_downloads ||= current_user.group_by_editals.paginate(:page => params[:download_page], :per_page=>10) %>

	<ul>
		<%=render @user_downloads %>
	</ul>

	<%= will_paginate @user_downloads, :param_name => 'download_page' %>
<% end %> 

app/views/downloads/_form.html.erb
<div id="edital_titulo">
	<p>
		<%= wrap("#{@edital.modalidade.descricao} #{@edital.numero_licitacao}/#{@edital.ano_licitacao}") %>
	</p>

	<p>
		<%= wrap(@edital.descricao) %>
	</p>
</div>


<div id="link">
		<%= form_for [@edital, @download], :remote=>true  do |f| %>

			<%= f.hidden_field :edital_id, "value" => @edital.id %>
			<%= f.hidden_field :user_id, "value" => current_user.id %>

			<%= f.submit "Download !",:id=>"submit_download", :class => "signup_button round" %>
		<% end %>
</div>



	<% if current_user.admin?%>
		<hr />
		<div id="edital<%= @edital.id %>" class="sidebar round"> 
			<%= render 'count', :id=>@edital.id%>
		</div>
	<% end %>	

	<% if current_user.admin? %>
		<%=  link_to  "Propostas", @edital,:class=>"g-button" %>
	<% else %>
		<%=  link_to  "Upload de Proposta", @edital,:class=>"g-button" %>
	<% end %>
	
<div>

app/views/downloads/_list.html.erb
<div id="edital_titulo">
	<p>
		<%= wrap("#{@edital.modalidade.descricao} #{@edital.numero_licitacao}/#{@edital.ano_licitacao}") %>
	</p>

	<p>
		<%= wrap(@edital.descricao) %>
	</p>
</div>

<p>
<div id="link">
	<%= link_to "Download!" , edital_downloads_path(@edital), :method=>:post, :class => "signup_button round" %>
</p>


	<% if current_user.admin?%>
		<hr />
		<div id="edital<%= @edital.id %>" class="sidebar round"> 
			<%= render 'count', :id=>@edital.id%>
		</div>
	<% end %>	

	<% if current_user.admin? %>
		<%=  link_to  "Propostas", @edital %>
	<% else %>
		<%=  link_to  "Upload de Proposta", @edital %>
	<% end %>
	
<div>

app/views/downloads/create.js.erb
$("#stats").html("<%= escape_javascript(render 'shared/stats') %>");

window.location.href="<%=download_url(@edital)%>";

app/views/downloads/index.js.erb
$("#stats").html("<%= escape_javascript(render 'shared/stats') %>");

app/views/downloads/new.html.erb
<% title "Download" %>

<% @user ||= current_user %>

	<table class="front" summary="For signed-in users">

		<tr>

			<td class="main">
				<div id="microposts">
						<%= render 'form' %>				
				</div>
			</td>
	
			<% if logged_in? %>
				<td class="sidebar">
					<div id="stats" class="round">					
						<%= render 'shared/stats' %>	
					<div>
				</td>
			<% end %>

		</tr>

	</table>

app/views/downloads/new.js.erb
$('#user_downloads').html("<%= escape_javascript( render 'downloads/downloads' )%>");

app/views/downloads/show.js.erb
$('#user_downloads').html("<%= escape_javascript( render 'downloads/downloads' )%>");