config/routes.rb
Gereditais::Application.routes.draw do

	resources :ceps
	
	resources :sessions
	resources :users

	resources :modalidades

	resources :editals do
		member do
			get 'edital'
		end

		resources :downloads

		resources :uploads do
			member do
				get 'upload'
			end
		end

		resources :impugnations do
			member do
				get 'impugnation'
			end
		end

		resources :microposts

	end

	match 'signup' => 'users#new', :as => :signup
	match 'logout' => 'sessions#destroy', :as => :logout
	match 'login' => 'sessions#new', :as => :login

	match 'products' => redirect('http://apps.ghc.com.br/gerestoque'), :as=>:products

	root :to=> "editals#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
# encoding: utf-8

class User < ActiveRecord::Base

	before_save :prepare_password, :valida_cnpj_cpf
	after_save :grava_mumps

	has_many :download , :dependent => :destroy
	has_many :edital , :through=> :download 
	has_many :upload , :dependent => :destroy
	has_many :impugnation , :dependent => :destroy
	has_many :micropost , :dependent => :destroy

	# new columns need to be added here to be writable through mass assignment
	attr_accessible :username, :email, :password, :password_confirmation, :cnpj_cpf,	
							:razao_social,:fone, :fax, :contato, 
							:cep, :logradouro, :numero, :complemento, :bairro, :cidade, 
							:uf, :inscr_estatual

	attr_accessor :password

	validates_presence_of :cnpj_cpf, :razao_social

	validates_presence_of :username
	validates_uniqueness_of :username, :cnpj_cpf , :allow_blank => false

#	CPF  = /\d{3}\.\d{3}\.\d{3}\-\d{2}/
#	CNPJ = /\d{2}\.\d{3}\.\d{3}\/\d{4}\-\d{2}/
	CPF  = /\d{11}/
	CNPJ = /\d{14}/

	validates_format_of :cnpj_cpf, :with =>/^(#{CPF})|(#{CNPJ})$/, :allow_blank => false, :message => "CPF ou CNPJ formato inválido", :uniqueness =>{:case_sensitive => false}

	validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => false, :message => "Apenas letras, numeros, ou .-_@"

#	EMAIL= /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/x
	EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates_format_of :email, :with =>/^(#{EMAIL})$/ , :allow_blank => true
	
	validates_presence_of :password, :on => :create
	validates_confirmation_of :password, :on=> :create
	validates_length_of :password, :minimum => 4, :allow_blank => false , :on=>:create

  # login can be either username or cnpj_cpf
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_cnpj_cpf(login)
    return user if user && user.matching_password?(pass)
  end

  def matching_password?(pass)
    self.password_hash == encrypt_password(pass)
  end

	def group_by_editals
		begin
			download.group("edital_id").select("edital_id, count(edital_id) as edital_count")
		rescue
			[]
		end
	end


# exporta cadastro para base mumps
	def grava_mumps

	str="#{self.username}^#{self.email}^#{self.cnpj_cpf}^#{self.razao_social}^#{self.fone}^#{self.fax}^#{self.contato}^#{self.cep}^#{self.logradouro}^#{self.numero}^#{self.complemento}^#{self.bairro}^#{self.cidade}^#{self.uf}^#{self.inscr_estatual}"
		
		logger.info(str)		
		begin
			ret=ControllerConsomewsghc::wsghc(:id=>14,:param=>str)
		rescue
		end
	end



private


  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end
  
  def valida_cnpj_cpf
  	
  	if self.cnpj_cpf.to_s.gsub(/[.-]/,'').length==11

		cpf=self.cnpj_cpf.to_s

		val=cpf.gsub(/[.-]/,'')

		_9=val[0..8]
		_dv=val[9..11]

		_9v=_9.split(//)
		_9n=[]
		10.downto(2) { |n| _9n << n.to_s }

		_tot=[]
		_9n.each_index { |n| _tot << _9n[n].to_i * _9v[n].to_i }

		tot=0
		_tot.each { |n| tot=tot+n }

		div=tot/11
		mod=tot%11

		if mod<2
			_dv1=0
		else
			_dv1=11-mod
		end

		_9v << _dv1

		_9n=[]
		11.downto(2) { |n| _9n << n.to_s }

		_tot=[]
		_9n.each_index { |n| _tot << _9n[n].to_i * _9v[n].to_i }

		tot=0
		_tot.each { |n| tot=tot+n }

		div=tot/11
		mod=tot%11

		if mod<2
			_dv2=0
		else
			_dv2=11-mod
		end

		_dvc="#{_dv1}#{_dv2}"
	
		if _dvc != _dv then
			errors.add(:cnpj_cpf,"'CPF #{self.cnpj_cpf}', digito verificador inválido")
			return false
		end

  	elsif self.cnpj_cpf.to_s.gsub(/[.-]/,'').gsub(/[\/]/,'').length==14

		cnpj=self.cnpj_cpf.to_s
		val=cnpj.gsub(/[.-]/,'').gsub(/[\/]/,'')

		_12=val[0..11]
		_dv=val[12..14]

		_12v=_12.split(//)
		_12n=[]
		[5,4,3,2,9,8,7,6,5,4,3,2].each { |n| _12n << n.to_s }

		_tot=[]
		_12n.each_index { |n| _tot << _12n[n].to_i * _12v[n].to_i }

		tot=0
		_tot.each { |n| tot=tot+n }

		div=tot/11
		mod=tot%11

		if mod<2
			_dv1=0
		else
			_dv1=11-mod
		end

		_12v << _dv1

		_12n=[]
		[6,5,4,3,2,9,8,7,6,5,4,3,2].each { |n| _12n << n.to_s }

		_tot=[]
		_12n.each_index { |n| _tot << _12n[n].to_i * _12v[n].to_i }

		tot=0
		_tot.each { |n| tot=tot+n }

		div=tot/11
		mod=tot%11

		if mod<2
			_dv2=0
		else
			_dv2=11-mod
		end

		_dvc="#{_dv1}#{_dv2}"
	
		if _dvc != _dv then
			errors.add(:cnpj_cpf,"'CNPJ #{self.cnpj_cpf}', digito verificador inválido")
			return false
		end


	else
		errors.add(:cnpj_cpf,"'CNPJ ou CPF Inválido, tamanho para CPF 11 dígitos, tamanho para CNPJ 14 dígitos'")
		return false
  	end

  end
  
end

app/controllers/users_controller.rb
# encoding: utf-8

class UsersController < ApplicationController

  	before_filter :login_required, :except => [:new, :create]

	def index

		if logged_in? and current_user.admin?
			@users=User.scoped.paginate(:page => params[:page], :per_page=>10)
		else

		end
	
	end

  def show
    @user = User.find(params[:id])
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.accessible = :all if logged_in? and current_user.admin?    
    @user.attributes=params[:user]
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Perfil criado com sucesso, Voce está logado."
#		UserMailer.user_create(@user).deliver
		UserMailer.delay.user_create(@user)
      redirect_to root_path
    else
      render :action => 'new'
    end
  end

  def edit
#    @user = current_user
	
    @user = User.find(params[:id])
	 redirect_to root_path if current_user!=@user && current_user.admin==false

  end

  def update
#    @user = current_user
    @user = User.find(params[:id])
    @user.accessible = :all if logged_in? and current_user.admin?
   	
    if @user.update_attributes(params[:user])
      flash[:success] = "Perfil do usuário atualizado."
#  		UserMailer.user_update(@user).deliver
  		UserMailer.delay.user_update(@user) 
      redirect_to root_path
    else
      render :action => 'edit'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
 
<%= f.error_messages %>

<table>

<tr>
<td >

 <fieldset class="round"> 
 <legend>Dados para login</legend> 

	<div class="dados_usuario">
	  <p>
		 <%= f.label :username, "Usuario" %><br />
		 <%= f.text_field :username, :class=>"user_username" %>
		<span class="timestamp">Apenas letras, numeros, ou .-_@</span>
	  </p>
	  <p>
		 <%= f.label :email, "Email" %><br />
		 <%= f.text_field :email, :autocomplete=>"off" %>
	  </p>
	  <p>
		 <%= f.label :password , "Senha"%><br />
		 <%= f.password_field :password, :autocomplete=>"off" %>
	  </p>
	  <p>
		 <%= f.label :password_confirmation, "Confirma Senha" %><br />
		 <%= f.password_field :password_confirmation, :autocomplete=>"off" %>
	  </p>

	<% if logged_in? and current_user.admin? %>
	  <p>
		 <%= f.label :admin, "Administrator" %><br />
		 <%= f.check_box :admin %>
	  </p>
	<% end %>
	</div>

 </fieldset> 

</td>

<td>
</td>
</tr>
<tr>
</tr>

<tr>
<td >

<fieldset class="round"> 
 <legend>Dados da Empresa</legend> 

	<div class="dados_empresa">
	  <p>
		 <%= f.label :cnpj_cpf, "CNPJ ou CPF" %><br />
		 <%= f.text_field :cnpj_cpf %>
	<span class="timestamp">Apenas números</span>
	  </p>

	  <p>
		 <%= f.label :inscr_estatual, "inscrição Estatual" %><br />
		 <%= f.text_field :inscr_estatual %>
	  </p>


	  <p>
		 <%= f.label :razao_social, "Razão Social ou Nome completo" %><br />
		 <%= f.text_field :razao_social %>
	  </p>

	  <p>
		 <%= f.label :fone, "Fone" %><br />
		 <%= f.text_field :fone %>
	  </p>

	  <p>
		 <%= f.label :fax, "Fax" %><br />
		 <%= f.text_field :fax %>
	  </p>

	  <p>
		 <%= f.label :contato, "Contato" %><br />
		 <%= f.text_field :contato %>
	  </p>
	  <p>
	  &nbsp
	  </p>
	  <p>
	  &nbsp
	  </p>

	</div>

</fieldset> 

</td>

<td >

<fieldset class="round"> 
 <legend>Endereço da Empresa</legend> 

	<div class="endereco_empresa " id="endereco_empresa" data-root="<%=root_url%>" >
	  <p>
		 <%= f.label :cep, "CEP" %><br />
		 <%= f.text_field :cep , :class=>"text"%>
		<span id="wait_cep" style="display:none"> 
			<%= image_tag "indicator_arrows_circle.gif" %> Localizando ...
		</span> 
	  </p>

	  <p>
		 <%= f.label :logradouro, "Logradouro" %><br />
		 <%= f.text_field :logradouro, :readonly => true %>
	  </p>

	  <p>
		 <%= f.label :numero, "Número" %><br />
		 <%= f.text_field :numero%>
	  </p>

	  <p>
		 <%= f.label :complemento, "Complemento" %><br />
		 <%= f.text_field :complemento%>
	  </p>

	  <p>
		 <%= f.label :bairro, "Bairro" %><br />
		 <%= f.text_field :bairro, :readonly => true %>
	  </p>

	  <p>
		 <%= f.label :cidade, "Cidade" %><br />
		 <%= f.text_field :cidade, :readonly => true %>
	  </p>

	  <p>
		 <%= f.label :uf, "UF" %><br />
		 <%= f.text_field :uf , :readonly => true%>
	  </p>

	</div>

</fieldset> 


</td>
</tr>
</table>


<p><%= f.submit @user.new_record? ? "Salvar" : "Atualizar", :class=>"g-button" %></p>

 
<% end %>

app/views/users/_user.html.erb
<tr>


	<td class="micropost">
		<%= link_to "#{user.username} - #{user.razao_social}", user %>
		<% if current_user.admin? %>

<!--		( <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
																:title => "Delete #{user.username}" %> )-->
		<% end %>

	</td>

</tr>

app/views/users/_user_downloads.html.erb
	<% downloads ||= @user.group_by_editals.paginate(:page => params[:download_page], :per_page=>10)%>

	<ul>

	<% for download in downloads %>
	<li>
		<%= "#{download.edital.modalidade.descricao} #{download.edital.numero_licitacao}/#{download.edital.ano_licitacao}" %>
		<%= pluralize(download.edital_count, "Download") %>
	</li>
	<% end%>

	</ul>


	<%= will_paginate downloads, :param_name => 'download_page' %>

app/views/users/_user_stats.html.erb
	<p>
		<strong>Empresa:</strong> <%= @user.razao_social %>	
	</p>
	<p>
		<strong>Usuário:</strong> <%= @user.username %>
	</p>
	<p>
		<strong>Email:</strong> <%= @user.email %>
	</p>

	<span>
		<%= pluralize(@user.edital.count, "Download") %>
	</span>

	<div id="user_downloads">	 				
		<%=render 'user_downloads'%>
	</div>

app/views/users/edit.html.erb
<% title "Atualização do Perfil" %>

<%= render 'form' %>

app/views/users/index.html.erb
<% title "Lista de Usuários" %>

<% if logged_in? and current_user.admin? %>

	<%= will_paginate @users %>
	<table class="usuarios" summary="Users">
		<%= render @users %>
	</table>
	<%= will_paginate @users %>

<% end %>

app/views/users/new.html.erb
<% title "Novo Cadastro" %>

<p>Já possui cadastro? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>

app/views/users/show.html.erb
<% title "Dados do Usuário" %>
<% if @user %>

	<table class="profile" summary="Profile information">
	<tr>
		<td class="main">

			<h3>
				<strong>Empresa: </strong> <%= @user.razao_social %>
			</h3>

			<h3>
				<strong>CNPJ / CPF: </strong><%= @user.cnpj_cpf %>
			</h3>


			<h3>
				<strong>usuário: </strong><%= @user.username %>
			</h3>

			<h3>
				<strong>email: </strong>	<%= @user.email %>
			</h3>

			<h3>
				<strong>fone: </strong>	<%= @user.fone %>
			</h3>

			<h3>
				<strong>fax: </strong>	<%= @user.fax %>
			</h3>

			<h3>
				<strong>Contato: </strong>	<%= @user.contato %>
			</h3>

			<h3>
				<strong>Pass: </strong>	

				<%  
					begin	
						ret =ControllerConsomewsghc::wsghc(:id=>12,:param=>@user.cnpj_cpf.gsub(/\./,"").gsub(/\//,"").gsub(/\-/,"")) 
					rescue
					end
				%>
				<%=
					begin 
						ret.split("^")[2] 
					rescue 
					end
				%>
			</h3>

		<% if current_user.admin?%>
			<%= link_to "Editar perfil do usuário", edit_user_path(@user) %>
		<% end %>

		</td>

		<td class="sidebar round">
			<%= render 'user_stats' %>
		</td>

	</tr>

	</table>

<% end %>

app/views/users/show.js.erb
$('#user_downloads').html("<%= escape_javascript( render 'user_downloads' )%>");