config/routes.rb
Gereditais::Application.routes.draw do

	resources :ceps
	
	resources :sessions
	resources :users

	resources :modalidades

	resources :editals do
		member do
			get 'edital'
		end

		resources :downloads

		resources :uploads do
			member do
				get 'upload'
			end
		end

		resources :impugnations do
			member do
				get 'impugnation'
			end
		end

		resources :microposts

	end

	match 'signup' => 'users#new', :as => :signup
	match 'logout' => 'sessions#destroy', :as => :logout
	match 'login' => 'sessions#new', :as => :login

	match 'products' => redirect('http://apps.ghc.com.br/gerestoque'), :as=>:products

	root :to=> "editals#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/modalidade.rb
# encoding: utf-8

class Modalidade < ActiveRecord::Base

	has_many :edital , :dependent => :destroy

	attr_accessible :codigo, :descricao

	validates_presence_of :codigo,:descricao

	validates_numericality_of :codigo


end

app/controllers/modalidades_controller.rb
# encoding: utf-8

class ModalidadesController < ApplicationController

	before_filter :login_required, :except => [:index, :show]
	before_filter :check_admin, :except => [:index, :show]
	
  def index
    @modalidades = Modalidade.scoped
  end
  
  def show
    @modalidade = Modalidade.find(params[:id])
  end
  
  def new
    @modalidade = Modalidade.new
  end
  
  def create
    @modalidade = Modalidade.new(params[:modalidade])
    if @modalidade.save
      flash[:notice] = "Modalidade criada com sucesso."
      redirect_to @modalidade
    else
      render :action => 'new'
    end
  end
  
  def edit
    @modalidade = Modalidade.find(params[:id])
  end
  
  def update
    @modalidade = Modalidade.find(params[:id])
    if @modalidade.update_attributes(params[:modalidade])
      flash[:notice] = "Modalidade atualizada com sucesso."
      redirect_to @modalidade
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @modalidade = Modalidade.find(params[:id])
    @modalidade.destroy
    flash[:notice] = "Modalidade apagada com sucesso."
    redirect_to modalidades_url
  end
end

app/helpers/modalidades_helper.rb
module ModalidadesHelper
end

app/views/modalidades/_form.html.erb
<%= form_for @modalidade do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </p>
  <p>
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </p>
  <p><%= f.submit "Salvar",:class=>"g-button" %></p>
<% end %>

app/views/modalidades/edit.html.erb
<% title "Edita Modalidade" %>

<%= render 'form' %>

<p>
  <%= link_to "Exibe", @modalidade %> |
  <%= link_to "Exibe todas", modalidades_path %>
</p>

app/views/modalidades/index.html.erb
<% title "Modalidades" %>

<table>
  <tr>
    <th>Codigo</th>
    <th>Descricao</th>
  </tr>
  <% for modalidade in @modalidades %>
    <tr>
      <td><%= modalidade.codigo %></td>
      <td><%= modalidade.descricao %></td>
      <td><%= link_to "Exibir", modalidade %></td>

		<% if logged_in? %>
		   <td><%= link_to "Editar", edit_modalidade_path(modalidade) %></td>
		   <td><%= link_to "Apagar", modalidade, :confirm => 'Are you sure?', :method => :delete %></td>
		<% end %>
    </tr>
  <% end %>
</table>

<% if logged_in? %>
<p><%= link_to "Nova Modalidade", new_modalidade_path %></p>
<% end %>

app/views/modalidades/new.html.erb
<% title "Nova Modalidade" %>

<%= render 'form' %>

<p><%= link_to "Lista de Modalidades", modalidades_path %></p>

app/views/modalidades/show.html.erb
<% title "Modalidade" %>

<p>
  <strong>Codigo:</strong>
  <%= @modalidade.codigo %>
</p>
<p>
  <strong>Descricao:</strong>
  <%= @modalidade.descricao %>
</p>

<p>
	<% if logged_in? %>
		<%= link_to "Editar", edit_modalidade_path(@modalidade) %> |
		<%= link_to "Apagar", @modalidade, :confirm => 'Are you sure?', :method => :delete %> |
		<%= link_to "Nova Modalidade", new_modalidade_path %>
	<% else %>
		<%= link_to "Exibir Todas", modalidades_path %>
	<% end%>

</p>